---

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0